"""create api_tokens table

Revision ID: 075b2de9aec3
Revises: a9e911577323
Create Date: 2018-06-27 20:46:05.204692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075b2de9aec3'
down_revision = 'a9e911577323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_timestamp'), 'api_tokens', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_timestamp'), table_name='api_tokens')
    op.drop_table('api_tokens')
    # ### end Alembic commands ###
